import sys

# Check if a module has been imported
def is_imported (module_name : str) -> bool:
    return module_name in sys.modules
    

# Set a dictionary with all residue names and their equivalent letters
residue_name_letters = {
    # Amino acids
    'ALA':'A',
    'ALAN':'A',
    'ALAC':'A',
    'ARG':'R',
    'ARGN':'R',
    'ARGC':'R',
    'ASN':'N',
    'ASNN':'N',
    'ASNC':'N',
    'ASP':'D',
    'ASPN':'D',
    'ASPC':'D',
    'CYS':'C',
    'CYSN':'C',
    'CYSC':'C',
    'CYH':'C',
    'CSH':'C',
    'CSS':'C',
    'CYX':'C',
    'CYP':'C',
    'GLN':'Q',
    'GLNN':'Q',
    'GLNC':'Q',
    'GLU':'E',
    'GLUN':'E',
    'GLUC':'E',
    'GLY':'G',
    'GLYN':'G',
    'GLYC':'G',
    'HIS':'H',
    'HISN':'H',
    'HISC':'H',
    'HID':'H',
    'HIE':'H',
    'HIP':'H',
    'HSD':'H',
    'HSE':'H',
    'ILE':'I',
    'ILEN':'I',
    'ILEC':'I',
    'ILU':'I',
    'LEU':'L',
    'LEUN':'L',
    'LEUC':'L',
    'LYS':'K',
    'LYSN':'K',
    'LYSC':'K',
    'MET':'M',
    'METN':'M',
    'METC':'M',
    'PHE':'F',
    'PHEN':'F',
    'PHEC':'F',
    'PRO':'P',
    'PRON':'P',
    'PROC':'P',
    'PRØ':'P',
    'PR0':'P',
    'PRZ':'P',
    'SER':'S',
    'SERN':'S',
    'SERC':'S',
    'THR':'T',
    'THRN':'T',
    'THRC':'R',
    'TRP':'W',
    'TRPN':'W',
    'TRPC':'W',
    'TRY':'W',
    'TYR':'Y',
    'TYRN':'Y',
    'TYRC':'Y',
    'VAL':'V',
    'VALN':'V',
    'VALC':'V',
    # Nucleotides
    'A': 'A',
    'A3': 'A',
    'A5': 'A',
    'DA': 'A',
    'RA': 'A',
    'C': 'C',
    'C3': 'C',
    'C5': 'C',
    'DC': 'C',
    'RC': 'C',
    'T': 'T',
    'T3': 'T',
    'T5': 'T',
    'DT': 'T',
    'G': 'G',
    'G3': 'G',
    'G5': 'G',
    'DG': 'G',
    'RG': 'G',
    'U': 'U',
    'U3': 'U',
    'U5': 'U',
    'RU': 'U'
}

# Given a residue name, return its single letter
def residue_name_to_letter (residue_name : str) -> str:
    return residue_name_letters.get(residue_name, 'X')